Branch3
hapjs-platform/hapjs pull request #169
Opened 2022-06-16 07:48 UTC by mingcan-vivo

2022-06-17 09:13 UTC, jianghai33 requested changes

2022-06-17 09:13 UTC, jianghai33 commented on core/runtime/android/runtime/src/main/java/org/hapjs/model/videodata/VideoCacheData.java
> + * Copyright (C) 2021, hapjs.org. All rights reserved.
copyright不对, 后边还有不少文件

2022-06-17 09:14 UTC, jianghai33 requested changes

2022-06-17 09:14 UTC, jianghai33 commented on core/runtime/android/runtime/src/main/java/org/hapjs/model/videodata/VideoCacheData.java
> + * Copyright (C) 2021, hapjs.org. All rights reserved.
copyright不对, 不少文件都这样

2022-06-17 09:31 UTC, jianghai33 approved these changes

2022-06-17 09:34 UTC, jianbo-oppo approved these changes

2022-06-17 12:38 UTC, yanglijun-vivo commented on core/runtime/android/runtime/src/main/java/org/hapjs/model/videodata/VideoCacheData.java
> + * Copyright (c) 2021, the hapjs-platform Project Contributors
2022

2022-06-17 12:38 UTC, yanglijun-vivo commented on core/runtime/android/runtime/src/main/java/org/hapjs/model/videodata/VideoCacheManager.java
> + * Copyright (c) 2021, the hapjs-platform Project Contributors
2022

2022-06-20 02:37 UTC, yanglijun-vivo approved these changes

2022-06-20 02:39 UTC, merged