[#256]调试器setting部分改版与优化
hapjs-platform/hapjs pull request #257
Opened 2022-09-20 13:15 UTC by charles-chai

fix #256

2022-09-20 13:21 UTC, yangxiangwu-oppo approved these changes

2022-09-20 13:24 UTC, yangxiangwu-oppo approved these changes

2022-09-21 03:42 UTC, duanchaodc approved these changes

2022-09-21 06:16 UTC, jianghai33 requested changes

2022-09-21 06:16 UTC, jianghai33 commented on debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/widget/CustomEditTextPreference.java
> +package org.hapjs.debugger.widget;
copy right

2022-09-21 06:16 UTC, jianghai33 commented on debug/shell/android/app-impl/src/main/res/anim/bottom_in.xml
> +<?xml version="1.0" encoding="utf-8"?>
copy right

2022-09-21 06:16 UTC, jianghai33 commented on debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/widget/CustomEditTextPreferenceDialogFragment.java
> +package org.hapjs.debugger.widget;
copy right

2022-09-21 08:36 UTC, duanchaodc approved these changes

2022-09-21 08:37 UTC, jianghai33 approved these changes

2022-09-21 08:42 UTC, duanchaodc approved these changes

2022-09-21 10:14 UTC, chenyinli requested changes

2022-09-21 10:14 UTC, chenyinli commented on debug/shell/android/app-impl/src/main/java/org/hapjs/debugger/widget/CustomEditTextPreference.java
> + * Copyright (c) 2021, the hapjs-platform Project Contributors
copyright是2022

2022-09-21 12:15 UTC, duanchaodc approved these changes

2022-09-21 13:02 UTC, chenyinli approved these changes

2022-09-21 13:03 UTC, merged