[#271]download请求支持进度事件通知及abort能力
hapjs-platform/hapjs pull request #272
Opened 2022-09-21 08:27 UTC by jianghai33

fix #271

2022-09-22 02:36 UTC, charles-chai approved these changes

2022-09-22 03:17 UTC, jianbo-oppo approved these changes

2022-09-22 03:41 UTC, xiaomin1397 approved these changes

2022-09-22 09:06 UTC, jianbo-oppo approved these changes

2022-09-22 12:30 UTC, chenyinli requested changes

2022-09-22 12:30 UTC, chenyinli commented on core/runtime/android/features/src/main/java/org/hapjs/features/net/task/DownloadTask.java
> + * Copyright (C) 2022, hapjs.org. All rights reserved.
copyright

2022-09-22 12:30 UTC, chenyinli commented on core/runtime/android/features/src/main/java/org/hapjs/features/net/task/DownloadTaskImpl.java
> + * Copyright (C) 2022, hapjs.org. All rights reserved.
copyright

2022-09-22 13:14 UTC, jianghai33 commented on core/runtime/android/features/src/main/java/org/hapjs/features/net/task/DownloadTaskImpl.java
> + * Copyright (C) 2022, hapjs.org. All rights reserved.
done

2022-09-23 02:23 UTC, charles-chai approved these changes

2022-09-23 02:38 UTC, chenyinli approved these changes

2022-09-23 02:39 UTC, merged