[#262]渲染指令增加回调事件
hapjs-platform/hapjs pull request #279
Opened 2022-09-21 11:18 UTC by xiongliangoppo120

2022-09-21 12:17 UTC, chenyinli requested changes

2022-09-21 12:17 UTC, chenyinli commented on core/runtime/android/runtime/src/main/java/org/hapjs/render/CallBackJsUtils.java
> +package org.hapjs.render;
参考别的pr加上对应的 copyright

2022-09-22 02:34 UTC, chenyinli approved these changes

2022-09-22 02:47 UTC, chenjinfa-oppo approved these changes

2022-09-22 02:49 UTC, merged