通过provider返回statusbar高度, 便于定制 #13
hapjs-platform/hapjs pull request #29
Opened 2022-04-07 09:25 UTC by jianghai33

Change-Id: Id391cf79870220104b9a27f2bba2af33c8fa7f9b

2022-04-08 08:03 UTC, charles-chai approved these changes

2022-05-20 06:12 UTC, yangxiangwu-oppo approved these changes

2022-05-24 11:10 UTC, chenyinli requested changes

2022-05-24 11:10 UTC, chenyinli commented on core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/DefaultStatusBarSizeProvider.java
> + * Copyright (C) 2021, hapjs.org. All rights reserved.
copyright需按照项目要求

2022-05-24 11:10 UTC, chenyinli commented on core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/StatusBarSizeProvider.java
> + * Copyright (C) 2021, hapjs.org. All rights reserved.
copyright需按照项目要求

2022-05-24 11:57 UTC, jianghai33 commented on core/runtime/android/runtime/src/main/java/org/hapjs/common/utils/DefaultStatusBarSizeProvider.java
> + * Copyright (C) 2021, hapjs.org. All rights reserved.
done

2022-05-25 03:52 UTC, charles-chai approved these changes

2022-05-25 05:25 UTC, charles-chai approved these changes

2022-06-09 02:09 UTC, xiaominvivo approved these changes

2022-06-13 11:14 UTC, chenyinli approved these changes

2022-06-14 03:32 UTC, merged