[#287] 添桌组件
hapjs-platform/hapjs pull request #326
Opened 2022-09-22 07:22 UTC by mingcan-mc

fix #287

2022-09-22 08:42 UTC, charles-chai commented on core/runtime/android/widgets/src/main/java/org/hapjs/widgets/input/EventButton.java
> + * Copyright (C) 2022, hapjs.org. All rights reserved.
格式不对

2022-09-22 08:47 UTC, charles-chai approved these changes

2022-09-22 09:15 UTC, chenyinli requested changes

2022-09-22 09:15 UTC, chenyinli commented on core/framework/src/dsls/xvm/vm/index.js
> +        },
这个文件的头部改成2021-2022

2022-10-08 08:16 UTC, mingcan-mc commented
https://github.com/hapjs-platform/hapjs/pull/352

2022-10-08 08:16 UTC, closed without merging