[#401]for指令支持固定值
hapjs-platform/hapjs pull request #402
Opened 2022-09-26 13:31 UTC by ll-lilei

2022-09-29 06:18 UTC, MengWei-OPPO approved these changes

2022-10-08 03:46 UTC, panwen-xiaomi approved these changes

2022-10-08 04:22 UTC, chenyinli requested changes

2022-10-08 04:22 UTC, chenyinli commented on core/framework/test/suite/dsls/xvm/page/05.model/directive/for/base/index.test.js
> +
这个文件有修改，需要改头部2021-present

2022-10-08 04:22 UTC, chenyinli commented on core/framework/test/suite/dsls/xvm/page/05.model/directive/for/base/index.ux
> +    <div id="inst4">
这个文件有修改，需要改头部2021-present

2022-10-08 08:02 UTC, chenyinli approved these changes

2022-10-08 08:02 UTC, merged