[#403]增加父组件覆盖子组件样式能力
hapjs-platform/hapjs pull request #404
Opened 2022-09-26 13:36 UTC by ll-lilei

2022-09-27 04:08 UTC, panwen-xiaomi approved these changes

2022-09-28 02:34 UTC, MengWei-OPPO approved these changes

2022-10-08 04:13 UTC, chenyinli requested changes

2022-10-08 04:13 UTC, chenyinli commented on core/framework/test/suite/dsls/xvm/page/05.model/component/externalclasses/index.test.js
> + * Copyright (C) 2021-present, hapjs.org. All rights reserved.
/*
 * Copyright (c) 2021-present, the hapjs-platform Project Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

2022-10-08 08:04 UTC, chenyinli approved these changes

2022-10-08 08:04 UTC, merged