[#405]vm.$attrs 兼容先前版本
hapjs-platform/hapjs pull request #406
Opened 2022-09-26 13:43 UTC by ll-lilei

2022-09-27 02:09 UTC, MengWei-OPPO approved these changes

2022-09-29 06:30 UTC, MengWei-OPPO approved these changes

2022-09-29 08:00 UTC, chunge66 approved these changes

2022-10-08 04:10 UTC, chenyinli requested changes

2022-10-08 04:10 UTC, chenyinli commented on core/framework/src/dsls/xvm/vm/directive.js
> +    if ((!props || !props.hasOwnProperty(key)) && reservedAttr.indexOf(key) === -1) {
这个文件有修改，需要改头部为2021-present

2022-10-08 04:10 UTC, chenyinli commented on core/framework/test/suite/dsls/xvm/page/05.model/component/$attrs/index.test.js
> +      .to.include('part3')
这个文件有修改，需要改头部为2021-present

2022-10-08 04:10 UTC, chenyinli commented on core/framework/test/suite/dsls/xvm/page/05.model/component/array/index.test.js
> +    expect(warnMsgs[3])
这个文件有修改，需要改头部为2021-present

2022-10-08 08:06 UTC, chenyinli approved these changes

2022-10-08 08:06 UTC, merged