[#407]JS Framework日志优化
hapjs-platform/hapjs pull request #408
Opened 2022-09-27 01:08 UTC by ll-lilei

2022-09-27 04:11 UTC, panwen-xiaomi approved these changes

2022-10-08 04:21 UTC, chenyinli requested changes

2022-10-08 04:21 UTC, chenyinli commented on core/framework/src/dsls/xvm/app/bundle.js
> +  console.trace(`### App Framework ### 启动App---- ${name}`)
这个文件有修改，需要改头部2021-present

2022-10-08 04:21 UTC, chenyinli commented on core/framework/src/dsls/xvm/app/custom.js
> +    console.warn(`### App Framework ### app或inst不存在，注册自定义组件 '${name}' 失败`)
这个文件有修改，需要改头部2021-present

2022-10-08 04:21 UTC, chenyinli commented on core/framework/src/dsls/xvm/app/interface.js
> +    console.trace(`### App Framework ### 完成App初始化(${inst.id})----`)
这个文件有修改，需要改头部2021-present

2022-10-08 04:21 UTC, chenyinli commented on core/framework/src/dsls/xvm/page/bundle.js
> +  console.trace(`### App Framework ### 启动页面---- ${name}`)
这个文件有修改，需要改头部2021-present

2022-10-08 04:21 UTC, chenyinli commented on core/framework/src/dsls/xvm/page/executor.js
> +        console.warn(`### App Framework ### 页面元素更新循环次数已达：${taskLoopIndex}`)
这个文件有修改，需要改头部2021-present

2022-10-08 04:21 UTC, chenyinli commented on core/framework/src/dsls/xvm/plugin-i18n/index.js
> +      console.warn(`### App Framework ### i18n：locale文件中没有找到对应的key：${key}`)
这个文件有修改，需要改头部2021-present
另外这个文件的头部和同目录下的其他不一样，如果是用的开源代码，需要保留原始的版权信息。

2022-10-08 04:21 UTC, chenyinli commented on core/framework/src/dsls/xvm/vm/compiler.js
> +          `### App Framework ### for 循环数据的tid 属性 '${key}' 不唯一, 可能导致性能问题`
这个文件有修改，需要改头部2021-present

2022-10-08 04:21 UTC, chenyinli commented on core/framework/src/dsls/xvm/vm/directive.js
> +  if (!props) {
这个文件有修改，需要改头部2021-present

2022-10-08 04:21 UTC, chenyinli commented on core/framework/src/dsls/xvm/vm/watcher.js
> +            console.warn(
这个文件有修改，需要改头部2021-present

2022-10-08 04:21 UTC, chenyinli commented on core/framework/src/infras/bundles/parser/htmlparser.js
> +      console.error('### App Parser ### 解析错误：' + html)
这个文件有修改，需要改头部2021-present

2022-10-08 04:21 UTC, chenyinli commented on core/framework/src/infras/bundles/parser/transfer.js
> +                  console.warn('### App Parser ### ', v.log)
这个文件有修改，需要改头部2021-present

2022-10-08 04:21 UTC, chenyinli commented on core/framework/src/infras/dock/app/index.js
> -      console.warn(`### App Framework ### App 全局数据被清空`)
这个文件有修改，需要改头部2021-present

2022-10-08 04:21 UTC, chenyinli commented on core/framework/src/infras/platform/interface.js
> +        console.error(`### App Framework ### ${ret.toString()}`)
这个文件有修改，需要改头部2021-present

2022-10-08 04:21 UTC, chenyinli commented on core/framework/src/infras/platform/promise.js
> +      console.warn(`### App Framework ### Unhandled promise rejection: ${reason.stack}`)
这个文件有修改，需要改头部2021-present

2022-10-08 04:21 UTC, chenyinli commented on core/framework/src/infras/platform/session.js
> +      console.log(`### App Framework ### ${error}`)
这个文件有修改，需要改头部2021-present

2022-10-08 04:21 UTC, chenyinli commented on core/framework/src/infras/runtime/dom/nodes/element.js
> +const logOnceSet = new Set()
这个文件有修改，需要改头部2021-present

2022-10-08 04:21 UTC, chenyinli commented on core/framework/test/suite/dsls/xvm/page/05.model/state/undeclared/index.test.js
> +    expect(warnMessageList[2]).equal(
这个文件有修改，需要改头部2021-present

2022-10-08 07:51 UTC, ll-lilei commented on core/framework/src/dsls/xvm/plugin-i18n/index.js
> +      console.warn(`### App Framework ### i18n：locale文件中没有找到对应的key：${key}`)
此文件非其它开源文件

2022-10-08 10:03 UTC, chenyinli approved these changes

2022-10-08 10:04 UTC, merged