[#411] 全屏播放视频可截屏
hapjs-platform/hapjs pull request #412
Opened 2022-09-27 03:27 UTC by electrolyteJ

2022-09-27 04:09 UTC, jianghai33 commented
> 
fix #411

2022-09-27 04:10 UTC, jianghai33 requested changes

2022-09-27 04:10 UTC, jianghai33 commented on core/runtime/android/widgets/src/main/java/org/hapjs/widgets/video/Video.java
>  import android.content.Context;
Copyright (c) 2021需要修改Copyright (c) 2021-present

2022-09-27 06:29 UTC, tuozhaobing-vivo approved these changes

2022-09-27 07:08 UTC, xiongliangoppo120 approved these changes

2022-09-28 02:28 UTC, chenyinli approved these changes

2022-09-28 02:28 UTC, merged