[#458] 系统权限请求时候，相同权限不同接口同时请求会显示多次权限请求
hapjs-platform/hapjs pull request #463
Opened 2022-12-28 08:31 UTC by fengxiaochuan-xiaomi

优化系统权限请求方式，相同权限不同接口同时请求只显示一次权限请求

2022-12-29 02:50 UTC, fengxch commented
fix: https://github.com/hapjs-platform/hapjs/issues/458

2022-12-29 03:08 UTC, jianghai33 requested changes
copyright年份改成2021-2022

2022-12-29 03:09 UTC, jianghai33 commented on core/runtime/android/runtime/src/main/java/org/hapjs/bridge/permission/SystemPermissionManager.java
>  import android.app.Activity;
这个文件的copyright年份改成2021-2022

2022-12-29 06:44 UTC, jianghai33 approved these changes

2022-12-30 03:10 UTC, jianbo-oppo approved these changes

2022-12-30 05:23 UTC, chenyinli approved these changes

2022-12-30 05:24 UTC, merged